// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk8rtZchEGIWWsoyMD-ggZqJwsU2iKwOc',
    appId: '1:735996651489:web:619460c35974958b9fd4a0',
    messagingSenderId: '735996651489',
    projectId: 'fir-tutorial-7bbfc',
    authDomain: 'fir-tutorial-7bbfc.firebaseapp.com',
    storageBucket: 'fir-tutorial-7bbfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWlV-buDeUoK0LWDfT8-A_ybK5OvAmqSg',
    appId: '1:735996651489:android:ad263377206f40699fd4a0',
    messagingSenderId: '735996651489',
    projectId: 'fir-tutorial-7bbfc',
    storageBucket: 'fir-tutorial-7bbfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN3jObeeH8rfRVkUhLWNkJ0KAlCX4WeFg',
    appId: '1:735996651489:ios:6ae56f152951bfdb9fd4a0',
    messagingSenderId: '735996651489',
    projectId: 'fir-tutorial-7bbfc',
    storageBucket: 'fir-tutorial-7bbfc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN3jObeeH8rfRVkUhLWNkJ0KAlCX4WeFg',
    appId: '1:735996651489:ios:6ae56f152951bfdb9fd4a0',
    messagingSenderId: '735996651489',
    projectId: 'fir-tutorial-7bbfc',
    storageBucket: 'fir-tutorial-7bbfc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );
}
